# Generated by Django 4.1.4 on 2022-12-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Adeyinka', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='First Post', max_length=200),
        ),
    ]
